import { notFound } from 'next/navigation'

export const locales = ['en', 'ar', 'fr', 'de', 'ko', 'tr'] as const
export type Locale = (typeof locales)[number]
export const defaultLocale: Locale = 'en'

export function isLocale(value: string): value is Locale { return locales.includes(value as Locale) }
export function assertLocale(value: string): Locale { if (!isLocale(value)) notFound(); return value }
export function getDirection(locale: Locale): 'ltr' | 'rtl' { return locale === 'ar' ? 'rtl' : 'ltr' }
export function localizeHref(href: string, locale: Locale): string {
  if (!href.startsWith('/')) return href
  if (href === '/') return `/${locale}`
  if (href.startsWith(`/${locale}/`) || href === `/${locale}`) return href
  const hasLocale = locales.some((l) => href.startsWith(`/${l}/`) || href === `/${l}`)
  if (hasLocale) { const [, , ...parts] = href.split('/'); return `/${locale}/${parts.join('/')}`.replace(/\/$/, '') }
  return `/${locale}${href}`
}

export type Dictionary = {
  common: { language: string; region: string; shop: string; home: string; help: string; company: string; legal: string; copy: string; items: string; myWishlist: string; wishlistEmptyTitle: string; wishlistEmptyBody: string; discoverProducts: string; productNotFound: string; backToShop: string; purchased: string; account: string; wishlist: string; continueShopping: string; orderHistory: string; orderStatus: string; shippingAddress: string; trackingNumber: string; trackPackage: string; buyAgain: string; noOrdersYet: string; startShoppingToSeeOrders: string; shopNow: string; paymentMethods: string; addCard: string; noPaymentMethods: string; addCardToCheckout: string; savedAddresses: string; addAddress: string; defaultLabel: string; edit: string; setAsDefault: string; cancel: string; saveAddress: string; addToCart: string; bestSeller: string; new: string; qty: string; viewAll: string; viewOrder: string; totalOrders: string; wishlistItems: string; rewardPoints: string; recentOrders: string; signOut: string }
  header: { freeShipping: string; nav: { shop: string; new: string; bestSellers: string; story: string; help: string }; actions: { search: string; account: string; wishlist: string; cart: string; openMenu: string } }
  footer: { newsletterTitle: string; newsletterBody: string; emailPlaceholder: string; subscribe: string; subscribed: string; sections: { help: string; company: string; legal: string } }
  home: { discoverCollection: string; ourStory: string; browseAllCategories: string; exploreChapter: string; viewEntireEdit: string; addToCart: string; notAvailable: string; shopTheRitual: string; tryAiAssistant: string; viewShippingInfo: string; followInstagram: string; followTiktok: string; lovedBy: string; shopByConcern: string; joinCommunity: string; customerStories: string; targetedSolutions: string; shoppingDifferentRegion: string; marketMayVary: string }
  product: { addToCart: string; notAvailable: string; selectShade: string; breadcrumbHome: string; breadcrumbShop: string; notAvailableInRegionTitle: string; notAvailableInRegionBody: string }
  cart: { addToCart: string; title: string; emptyTitle: string; emptyBody: string; orderSummary: string; promoCode: string; enterCode: string; apply: string; subtotal: string; shipping: string; total: string; proceedToCheckout: string; freeShippingOver: string }
  search: { placeholder: string; trendingSearches: string; popularCategories: string; viewAllResults: string; resultsFor: string }
  ai: { title: string; subtitle: string; inputPlaceholder: string; startOver: string; typing: string; suggested: string; askPrompt: string }
  admin: {
    nav: Record<'dashboard'|'suppliers'|'products'|'regions'|'compliance'|'translations'|'media'|'social'|'ai'|'analytics'|'orders'|'customers', string>
    notifications: { title: string; markRead: string }
    searchPlaceholder: string
    aiCopilot: { title: string; description: string; draft: string; final: string; apply: string; generator: string; translator: string; marketer: string; tagging: string }
    translationCenter: { title: string; description: string; search: string; source: string; target: string; generate: string; improve: string; approve: string; saveDraft: string; preview: string }
  }
  regionMessages: Record<'visible_and_buyable'|'visible_but_not_buyable'|'hidden'|'pending_review', string>
}

const en: Dictionary = {
  common: { language: 'Language', region: 'Region', shop: 'Shop', home: 'Home', help: 'Help', company: 'Company', legal: 'Legal', copy: 'Copy', items: 'items', myWishlist: 'My Wishlist', wishlistEmptyTitle: 'Your wishlist is empty', wishlistEmptyBody: 'Save your favorite products to your wishlist for easy access later.', discoverProducts: 'Discover Products', productNotFound: 'Product not found', backToShop: 'Back to Shop', purchased: 'Purchased', account: 'Account', wishlist: 'Wishlist', continueShopping: 'Continue Shopping', orderHistory: 'Order History', orderStatus: 'Order Status', shippingAddress: 'Shipping Address', trackingNumber: 'Tracking Number', trackPackage: 'Track Package', buyAgain: 'Buy Again', noOrdersYet: 'No orders yet', startShoppingToSeeOrders: 'Start shopping to see your orders here.', shopNow: 'Shop Now', paymentMethods: 'Payment Methods', addCard: 'Add Card', noPaymentMethods: 'No payment methods', addCardToCheckout: 'Add a card to make checkout faster', savedAddresses: 'Saved Addresses', addAddress: 'Add Address', defaultLabel: 'Default', edit: 'Edit', setAsDefault: 'Set as Default', cancel: 'Cancel', saveAddress: 'Save Address', addToCart: 'Add to Cart', bestSeller: 'Best Seller', new: 'New', qty: 'Qty', viewAll: 'View All', viewOrder: 'View Order', totalOrders: 'Total Orders', wishlistItems: 'Wishlist Items', rewardPoints: 'Reward Points', recentOrders: 'Recent Orders', signOut: 'Sign Out' },
  header: { freeShipping: 'Free shipping on orders over {{amount}}', nav: { shop: 'Shop', new: 'New', bestSellers: 'Best Sellers', story: 'Our Story', help: 'Help' }, actions: { search: 'Search', account: 'Account', wishlist: 'Wishlist', cart: 'Cart', openMenu: 'Open menu' } },
  footer: { newsletterTitle: 'Join the JISOO Beauty Circle', newsletterBody: 'Be the first to know about new arrivals, exclusive offers, and K-beauty secrets.', emailPlaceholder: 'Enter your email', subscribe: 'Subscribe', subscribed: 'Thank you for subscribing! Welcome to the beauty circle.', sections: { help: 'Help', company: 'Company', legal: 'Legal' } },
  home: { discoverCollection: 'Discover Collection', ourStory: 'Our Story', browseAllCategories: 'Browse All Categories', exploreChapter: 'Explore Chapter', viewEntireEdit: 'View Entire Edit', addToCart: 'Add to Cart', notAvailable: 'Not Available', shopTheRitual: 'Shop the Ritual', tryAiAssistant: 'Try AI Assistant', viewShippingInfo: 'View Shipping Info', followInstagram: 'Follow on Instagram', followTiktok: 'Follow on TikTok', lovedBy: 'Loved by Beauty Enthusiasts', shopByConcern: 'Shop by Concern', joinCommunity: 'Join the Beauty Community', customerStories: 'Customer Stories', targetedSolutions: 'Targeted Solutions', shoppingDifferentRegion: 'Shopping from a different region?', marketMayVary: 'Some products may vary by market. Check availability for UAE, Europe, or Canada.' },
  product: { addToCart: 'Add to Cart', notAvailable: 'Not Available', selectShade: 'Select Shade', breadcrumbHome: 'Home', breadcrumbShop: 'Shop', notAvailableInRegionTitle: 'Not available in your region', notAvailableInRegionBody: 'This product is currently visible but not available for purchase in your region.' },
  cart: { addToCart: 'Add to Cart', title: 'Shopping Cart', emptyTitle: 'Your Cart is Empty', emptyBody: 'Discover our curated collection of premium Korean beauty products and start your skincare journey.', orderSummary: 'Order Summary', promoCode: 'Promo Code', enterCode: 'Enter code', apply: 'Apply', subtotal: 'Subtotal', shipping: 'Shipping', total: 'Total', proceedToCheckout: 'Proceed to Checkout', freeShippingOver: 'Free shipping on orders over' },
  search: { placeholder: 'Search for products, ingredients, concerns...', trendingSearches: 'Trending Searches', popularCategories: 'Popular Categories', viewAllResults: 'View all results', resultsFor: 'results for' },
  ai: { title: 'JISOO AI Consultant', subtitle: 'Grounded recommendations from your catalog and region', inputPlaceholder: 'Ask about concerns, availability, or product comparison…', startOver: 'Start Over', typing: 'JISOO AI is thinking…', suggested: 'Suggested questions', askPrompt: 'Ask for availability, concerns, or product comparisons.' },
  admin: { nav: { dashboard: 'Dashboard', suppliers: 'Suppliers', products: 'Products', regions: 'Regions', compliance: 'Compliance', translations: 'Translations', media: 'Media', social: 'Social', ai: 'AI Copilot', analytics: 'Analytics', orders: 'Orders', customers: 'Customers' }, notifications: { title: 'Notifications', markRead: 'Mark all read' }, searchPlaceholder: 'Search products, orders, customers...', aiCopilot: { title: 'AI Operations Copilot', description: 'Generate product copy, translations, marketing text, and tags from local catalog context.', draft: 'Draft', final: 'Final', apply: 'Apply', generator: 'Description Generator', translator: 'Translation Generator', marketer: 'Luxury Tone Rewriter', tagging: 'Tag & Category Assistant' }, translationCenter: { title: 'Translation Center', description: 'Manage source text, AI drafts, edits, approvals, and preview across locales.', search: 'Search fields…', source: 'Source', target: 'Target', generate: 'Generate Translation', improve: 'Improve Luxury Tone', approve: 'Approve', saveDraft: 'Save Draft', preview: 'Preview' } },
  regionMessages: { visible_and_buyable: 'Available in your region', visible_but_not_buyable: 'Visible now, purchasing opens soon in your region', hidden: 'Unavailable in your selected region', pending_review: 'Pending compliance review for your region' },
}

const fr: Dictionary = { ...en, common: { ...en.common, language: 'Langue', region: 'Région', shop: 'Boutique', help: 'Aide', company: 'Entreprise', legal: 'Légal' }, header: { ...en.header, nav: { shop: 'Boutique', new: 'Nouveau', bestSellers: 'Meilleures ventes', story: 'Notre histoire', help: 'Aide' }, actions: { search: 'Rechercher', account: 'Compte', wishlist: 'Liste d’envies', cart: 'Panier', openMenu: 'Ouvrir le menu' } }, ai: { ...en.ai, title: 'Concierge IA JISOO' }, home: { ...en.home, discoverCollection: 'Découvrir la collection', ourStory: 'Notre histoire', browseAllCategories: 'Parcourir toutes les catégories', exploreChapter: 'Explorer ce chapitre', viewEntireEdit: 'Voir toute la sélection', addToCart: 'Ajouter au panier', notAvailable: 'Indisponible', shopTheRitual: 'Acheter le rituel', tryAiAssistant: 'Essayer l’Assistant IA', viewShippingInfo: 'Voir les infos de livraison', followInstagram: 'Suivre sur Instagram', followTiktok: 'Suivre sur TikTok', lovedBy: 'Adoré par les passionnés de beauté', shopByConcern: 'Acheter par besoin', joinCommunity: 'Rejoindre la communauté beauté', customerStories: 'Témoignages clients', targetedSolutions: 'Solutions ciblées', shoppingDifferentRegion: 'Vous achetez depuis une autre région ?', marketMayVary: 'Certains produits peuvent varier selon le marché. Vérifiez la disponibilité pour les Émirats, l’Europe ou le Canada.' }, product: { ...en.product, addToCart: 'Ajouter au panier', notAvailable: 'Indisponible', selectShade: 'Choisir la teinte', notAvailableInRegionTitle: 'Indisponible dans votre région', notAvailableInRegionBody: 'Ce produit est visible mais actuellement indisponible à l’achat dans votre région.' }, cart: { ...en.cart, addToCart: 'Ajouter au panier', title: 'Panier', emptyTitle: 'Votre panier est vide', emptyBody: 'Découvrez notre sélection de soins coréens premium et commencez votre rituel beauté.', orderSummary: 'Récapitulatif', promoCode: 'Code promo', enterCode: 'Entrer le code', apply: 'Appliquer', subtotal: 'Sous-total', shipping: 'Livraison', total: 'Total', proceedToCheckout: 'Passer à la caisse', freeShippingOver: 'Livraison offerte dès' }, search: { ...en.search, placeholder: 'Rechercher des produits, ingrédients, besoins…', trendingSearches: 'Recherches tendances', popularCategories: 'Catégories populaires', viewAllResults: 'Voir tous les résultats', resultsFor: 'résultats pour' } }
const de: Dictionary = { ...en, common: { ...en.common, language: 'Sprache', region: 'Region', shop: 'Shop', help: 'Hilfe', company: 'Unternehmen', legal: 'Rechtliches' }, header: { ...en.header, nav: { shop: 'Shop', new: 'Neu', bestSellers: 'Bestseller', story: 'Unsere Geschichte', help: 'Hilfe' }, actions: { search: 'Suchen', account: 'Konto', wishlist: 'Wunschliste', cart: 'Warenkorb', openMenu: 'Menü öffnen' } }, ai: { ...en.ai, title: 'JISOO KI-Beratung' }, home: { ...en.home, discoverCollection: 'Kollektion entdecken', ourStory: 'Unsere Geschichte', browseAllCategories: 'Alle Kategorien ansehen', exploreChapter: 'Kapitel entdecken', viewEntireEdit: 'Gesamte Auswahl anzeigen', addToCart: 'In den Warenkorb', notAvailable: 'Nicht verfügbar', shopTheRitual: 'Ritual shoppen', tryAiAssistant: 'KI-Assistent testen', viewShippingInfo: 'Versandinfos anzeigen', followInstagram: 'Auf Instagram folgen', followTiktok: 'Auf TikTok folgen', lovedBy: 'Beliebt bei Beauty-Fans', shopByConcern: 'Nach Hautthema shoppen', joinCommunity: 'Der Beauty-Community beitreten', customerStories: 'Kundengeschichten', targetedSolutions: 'Gezielte Lösungen', shoppingDifferentRegion: 'Kaufst du aus einer anderen Region?', marketMayVary: 'Einige Produkte variieren je nach Markt. Verfügbarkeit für VAE, Europa oder Kanada prüfen.' }, product: { ...en.product, addToCart: 'In den Warenkorb', notAvailable: 'Nicht verfügbar', selectShade: 'Farbton auswählen', notAvailableInRegionTitle: 'In deiner Region nicht verfügbar', notAvailableInRegionBody: 'Dieses Produkt ist sichtbar, aber in deiner Region derzeit nicht kaufbar.' }, cart: { ...en.cart, addToCart: 'In den Warenkorb', title: 'Warenkorb', emptyTitle: 'Dein Warenkorb ist leer', emptyBody: 'Entdecke unsere kuratierte Auswahl an Premium-K-Beauty-Produkten.', orderSummary: 'Bestellübersicht', promoCode: 'Gutscheincode', enterCode: 'Code eingeben', apply: 'Anwenden', subtotal: 'Zwischensumme', shipping: 'Versand', total: 'Gesamt', proceedToCheckout: 'Zur Kasse', freeShippingOver: 'Kostenloser Versand ab' }, search: { ...en.search, placeholder: 'Produkte, Inhaltsstoffe, Bedürfnisse suchen…', trendingSearches: 'Trend-Suchen', popularCategories: 'Beliebte Kategorien', viewAllResults: 'Alle Ergebnisse anzeigen', resultsFor: 'Ergebnisse für' } }
const ko: Dictionary = { ...en, common: { ...en.common, language: '언어', region: '지역', shop: '쇼핑', help: '도움말', company: '회사', legal: '법률', copy: '복사', items: '개', myWishlist: '위시리스트', wishlistEmptyTitle: '위시리스트가 비어 있습니다', wishlistEmptyBody: '나중에 쉽게 확인할 수 있도록 좋아하는 상품을 저장하세요.', discoverProducts: '상품 둘러보기', productNotFound: '상품을 찾을 수 없습니다', backToShop: '쇼핑으로 돌아가기', purchased: '구매 상품', account: '계정', wishlist: '위시리스트', continueShopping: '쇼핑 계속하기', shopNow: '쇼핑하기', addToCart: '장바구니 담기' }, header: { ...en.header, nav: { shop: '쇼핑', new: '신상품', bestSellers: '베스트셀러', story: '브랜드 스토리', help: '도움말' }, actions: { search: '검색', account: '계정', wishlist: '위시리스트', cart: '장바구니', openMenu: '메뉴 열기' } }, ai: { ...en.ai, title: 'JISOO AI 컨설턴트' }, home: { ...en.home, discoverCollection: '컬렉션 보기', ourStory: '브랜드 스토리', browseAllCategories: '전체 카테고리 보기', exploreChapter: '챕터 보기', viewEntireEdit: '전체 에디트 보기', addToCart: '장바구니 담기', notAvailable: '구매 불가', shopTheRitual: '리추얼 쇼핑', tryAiAssistant: 'AI 어시스턴트 체험', viewShippingInfo: '배송 정보 보기', followInstagram: '인스타그램 팔로우', followTiktok: '틱톡 팔로우', lovedBy: '뷰티 애호가들의 선택', shopByConcern: '피부 고민별 쇼핑', joinCommunity: '뷰티 커뮤니티 참여', customerStories: '고객 후기', targetedSolutions: '맞춤 솔루션', shoppingDifferentRegion: '다른 지역에서 쇼핑 중이신가요?', marketMayVary: '시장별로 일부 제품 구성이 다를 수 있습니다. UAE, 유럽, 캐나다 재고를 확인하세요.' }, product: { ...en.product, addToCart: '장바구니 담기', notAvailable: '구매 불가', selectShade: '쉐이드 선택', breadcrumbHome: '홈', breadcrumbShop: '쇼핑', notAvailableInRegionTitle: '현재 지역에서는 구매할 수 없습니다', notAvailableInRegionBody: '이 제품은 현재 고객님의 지역에서 노출만 되며 구매는 불가능합니다.' }, cart: { ...en.cart, addToCart: '장바구니 담기', title: '장바구니', emptyTitle: '장바구니가 비어 있습니다', emptyBody: '프리미엄 K-뷰티 큐레이션을 둘러보고 스킨케어 루틴을 시작해보세요.', orderSummary: '주문 요약', promoCode: '프로모션 코드', enterCode: '코드 입력', apply: '적용', subtotal: '소계', shipping: '배송비', total: '합계', proceedToCheckout: '결제하기', freeShippingOver: '이상 구매 시 무료배송' }, search: { ...en.search, placeholder: '제품, 성분, 고민 검색…', trendingSearches: '인기 검색어', popularCategories: '인기 카테고리', viewAllResults: '전체 결과 보기', resultsFor: '검색 결과' } }
const ar: Dictionary = { ...en, common: { ...en.common, language: 'اللغة', region: 'المنطقة', shop: 'المتجر', help: 'المساعدة', company: 'الشركة', legal: 'القانونية', copy: 'نسخ', items: 'عناصر', myWishlist: 'قائمة المفضلة', wishlistEmptyTitle: 'قائمة المفضلة فارغة', wishlistEmptyBody: 'احفظي منتجاتك المفضلة للوصول السريع لاحقًا.', discoverProducts: 'اكتشف المنتجات', productNotFound: 'المنتج غير موجود', backToShop: 'العودة إلى المتجر', purchased: 'تم الشراء', account: 'الحساب', wishlist: 'المفضلة', continueShopping: 'متابعة التسوق', shopNow: 'تسوّقي الآن', addToCart: 'أضف إلى السلة' }, header: { ...en.header, nav: { shop: 'المتجر', new: 'الجديد', bestSellers: 'الأكثر مبيعًا', story: 'قصتنا', help: 'المساعدة' }, actions: { search: 'بحث', account: 'الحساب', wishlist: 'المفضلة', cart: 'السلة', openMenu: 'فتح القائمة' } }, ai: { ...en.ai, title: 'مستشارة JISOO الذكية' }, home: { ...en.home, discoverCollection: 'اكتشفي المجموعة', ourStory: 'قصتنا', browseAllCategories: 'تصفح كل الفئات', exploreChapter: 'استكشفي الفصل', viewEntireEdit: 'عرض التحرير الكامل', addToCart: 'أضف إلى السلة', notAvailable: 'غير متاح', shopTheRitual: 'تسوّق الطقس', tryAiAssistant: 'جرّب مساعد الذكاء', viewShippingInfo: 'عرض معلومات الشحن', followInstagram: 'تابع على إنستغرام', followTiktok: 'تابع على تيك توك', lovedBy: 'محبوب من عشاق الجمال', shopByConcern: 'تسوّق حسب المشكلة', joinCommunity: 'انضم إلى مجتمع الجمال', customerStories: 'قصص العملاء', targetedSolutions: 'حلول موجهة', shoppingDifferentRegion: 'هل تتسوق من منطقة مختلفة؟', marketMayVary: 'قد تختلف بعض المنتجات حسب السوق. تحققي من التوفر للإمارات وأوروبا وكندا.' }, product: { ...en.product, addToCart: 'أضف إلى السلة', notAvailable: 'غير متاح', selectShade: 'اختيار الدرجة', notAvailableInRegionTitle: 'غير متاح في منطقتك', notAvailableInRegionBody: 'هذا المنتج ظاهر حاليًا لكنه غير متاح للشراء في منطقتك.' }, cart: { ...en.cart, addToCart: 'أضف إلى السلة', title: 'سلة التسوق', emptyTitle: 'سلة التسوق فارغة', emptyBody: 'اكتشفي مجموعتنا المختارة من منتجات الجمال الكورية الفاخرة.', orderSummary: 'ملخص الطلب', promoCode: 'رمز الخصم', enterCode: 'أدخل الرمز', apply: 'تطبيق', subtotal: 'المجموع الفرعي', shipping: 'الشحن', total: 'الإجمالي', proceedToCheckout: 'إتمام الشراء', freeShippingOver: 'شحن مجاني للطلبات فوق' }, search: { ...en.search, placeholder: 'ابحثي عن المنتجات أو المكونات أو المشكلات…', trendingSearches: 'عمليات البحث الرائجة', popularCategories: 'الفئات الشائعة', viewAllResults: 'عرض كل النتائج', resultsFor: 'نتائج لـ' } }
const tr: Dictionary = { ...en, common: { ...en.common, language: 'Dil', region: 'Bölge', shop: 'Mağaza', help: 'Yardım', company: 'Şirket', legal: 'Yasal' }, header: { ...en.header, nav: { shop: 'Mağaza', new: 'Yeni', bestSellers: 'Çok Satanlar', story: 'Hikayemiz', help: 'Yardım' }, actions: { search: 'Ara', account: 'Hesap', wishlist: 'Favoriler', cart: 'Sepet', openMenu: 'Menüyü aç' } }, ai: { ...en.ai, title: 'JISOO AI Danışmanı' }, home: { ...en.home, discoverCollection: 'Koleksiyonu Keşfet', ourStory: 'Hikayemiz', browseAllCategories: 'Tüm Kategoriler', exploreChapter: 'Bölümü İncele', viewEntireEdit: 'Tüm Seçkiyi Gör', addToCart: 'Sepete Ekle', notAvailable: 'Mevcut Değil', shopTheRitual: 'Rutini Satın Al', tryAiAssistant: 'AI Asistanı Dene', viewShippingInfo: 'Kargo Bilgisini Gör', followInstagram: 'Instagram’da Takip Et', followTiktok: 'TikTok’ta Takip Et', lovedBy: 'Güzellik Tutkunlarının Favorisi', shopByConcern: 'İhtiyaca Göre Alışveriş', joinCommunity: 'Güzellik Topluluğuna Katıl', customerStories: 'Müşteri Hikayeleri', targetedSolutions: 'Hedefe Yönelik Çözümler', shoppingDifferentRegion: 'Farklı bir bölgeden mi alışveriş yapıyorsunuz?', marketMayVary: 'Bazı ürünler pazara göre değişebilir. BAE, Avrupa veya Kanada için uygunluğu kontrol edin.' }, product: { ...en.product, addToCart: 'Sepete Ekle', notAvailable: 'Mevcut Değil', selectShade: 'Ton Seç', breadcrumbHome: 'Ana Sayfa', breadcrumbShop: 'Mağaza', notAvailableInRegionTitle: 'Bölgenizde mevcut değil', notAvailableInRegionBody: 'Bu ürün bölgenizde görüntüleniyor ancak şu anda satın alınamıyor.' }, cart: { ...en.cart, addToCart: 'Sepete Ekle', title: 'Alışveriş Sepeti', emptyTitle: 'Sepetiniz Boş', emptyBody: 'Premium Kore güzellik koleksiyonumuzu keşfedin ve bakım rutininize başlayın.', orderSummary: 'Sipariş Özeti', promoCode: 'Promosyon Kodu', enterCode: 'Kod girin', apply: 'Uygula', subtotal: 'Ara Toplam', shipping: 'Kargo', total: 'Toplam', proceedToCheckout: 'Ödemeye Geç', freeShippingOver: 'Şu tutar üzeri ücretsiz kargo' }, search: { ...en.search, placeholder: 'Ürün, içerik, cilt ihtiyacı ara…', trendingSearches: 'Popüler Aramalar', popularCategories: 'Popüler Kategoriler', viewAllResults: 'Tüm sonuçları gör', resultsFor: 'için sonuçlar' } }

export const dictionaries: Record<Locale, Dictionary> = { en, ar, fr, de, ko, tr }
export function getDictionary(locale: Locale): Dictionary { return dictionaries[locale] }
