// Admin Mock Data for JISOO Operations Platform
import type {
  Supplier,
  SupplierProduct,
  SupplierNotification,
  MarketAvailability,
  ComplianceRecord,
  ComplianceDocument,
  ComplaintRecord,
  TranslationTask,
  TranslationEntry,
  MediaAsset,
  SocialPost,
  AnalyticsDashboard,
  AIInsight,
  AdminDashboardData,
  ActivityItem,
  PendingAction,
  AdminOrder,
  AdminCustomer,
  ProductPerformance,
} from './types'

// ============ Suppliers ============
export const suppliers: Supplier[] = [
  {
    id: 'supplier-1',
    name: 'Hanbang Lab',
    code: 'HBL',
    logo: '/suppliers/hanbang-lab.png',
    location: 'Seoul, South Korea',
    description: 'Traditional Korean herbal beauty innovations with modern science.',
    specialization: 'Fermented Skincare & Herbal Formulations',
    lastSyncAt: '2024-03-15T09:30:00Z',
    syncStatus: 'synced',
    totalProducts: 45,
    pendingProducts: 3,
    activeProducts: 38,
    contactEmail: 'supply@hanbanglab.kr',
    contactName: 'Kim Soo-Jin',
    certifications: ['KFDA Certified', 'Cruelty-Free', 'Vegan Options'],
  },
  {
    id: 'supplier-2',
    name: 'Glow Research',
    code: 'GRW',
    logo: '/suppliers/glow-research.png',
    location: 'Incheon, South Korea',
    description: 'Cutting-edge dermatological research meets luxury beauty.',
    specialization: 'Brightening & Tone-Up Technology',
    lastSyncAt: '2024-03-15T08:15:00Z',
    syncStatus: 'synced',
    totalProducts: 62,
    pendingProducts: 5,
    activeProducts: 52,
    contactEmail: 'partners@glowresearch.co.kr',
    contactName: 'Park Min-Ho',
    certifications: ['ISO 22716', 'EWG Verified', 'Dermatologist Tested'],
  },
  {
    id: 'supplier-3',
    name: 'Seoul Skin Science',
    code: 'SSS',
    logo: '/suppliers/seoul-skin-science.png',
    location: 'Busan, South Korea',
    description: 'Clinical-grade skincare backed by decades of dermatological research.',
    specialization: 'Sensitive Skin & Clinical Solutions',
    lastSyncAt: '2024-03-14T22:00:00Z',
    syncStatus: 'syncing',
    totalProducts: 38,
    pendingProducts: 8,
    activeProducts: 28,
    contactEmail: 'b2b@seoulskinsci.com',
    contactName: 'Lee Hye-Won',
    certifications: ['Clinical Studies', 'Hypoallergenic', 'Fragrance-Free Options'],
  },
]

export const supplierProducts: SupplierProduct[] = [
  {
    id: 'sp-1',
    supplierId: 'supplier-1',
    supplierSku: 'HBL-SRM-001',
    name: 'Fermented Ginseng Renewal Serum',
    description: 'A potent anti-aging serum with 10-year fermented red ginseng extract.',
    price: 85,
    currency: 'EUR',
    images: ['/products/fermented-ginseng-serum.jpg'],
    category: 'serums',
    ingredients: ['Fermented Red Ginseng', 'Niacinamide', 'Adenosine'],
    changeType: 'new',
    status: 'pending',
    receivedAt: '2024-03-15T09:30:00Z',
  },
  {
    id: 'sp-2',
    supplierId: 'supplier-2',
    supplierSku: 'GRW-TNR-042',
    internalSku: 'JISOO-TNR-012',
    name: 'Crystal Glow Toner',
    description: 'Brightening toner with micro-pearl technology for instant radiance.',
    price: 42,
    currency: 'EUR',
    images: ['/products/crystal-glow-toner.jpg'],
    category: 'toners',
    ingredients: ['Micro-Pearl Complex', 'Vitamin C', 'Hyaluronic Acid'],
    changeType: 'updated',
    status: 'staged',
    previousVersion: {
      price: 38,
      description: 'Brightening toner with pearl technology.',
    },
    diff: [
      { field: 'price', oldValue: 38, newValue: 42 },
      { field: 'description', oldValue: 'Brightening toner with pearl technology.', newValue: 'Brightening toner with micro-pearl technology for instant radiance.' },
    ],
    receivedAt: '2024-03-14T14:20:00Z',
    processedAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'sp-3',
    supplierId: 'supplier-3',
    supplierSku: 'SSS-MSK-018',
    name: 'Centella Recovery Mask',
    description: 'Intensive soothing sheet mask with 95% Centella extract.',
    price: 8,
    currency: 'EUR',
    images: ['/products/centella-mask.jpg'],
    category: 'masks',
    ingredients: ['Centella Asiatica', 'Madecassoside', 'Panthenol'],
    changeType: 'new',
    status: 'approved',
    receivedAt: '2024-03-13T11:00:00Z',
    processedAt: '2024-03-14T09:30:00Z',
    processedBy: 'Admin User',
  },
  {
    id: 'sp-4',
    supplierId: 'supplier-1',
    supplierSku: 'HBL-CRM-033',
    name: 'Hanbang Herbal Night Cream',
    description: 'Rich night cream with traditional Korean herbs for overnight repair.',
    price: 72,
    currency: 'EUR',
    images: ['/products/herbal-night-cream.jpg'],
    category: 'moisturizers',
    ingredients: ['Licorice Root', 'Green Tea', 'Ginseng'],
    changeType: 'removed',
    status: 'pending',
    receivedAt: '2024-03-15T09:30:00Z',
    notes: 'Supplier discontinuing this product line',
  },
  {
    id: 'sp-5',
    supplierId: 'supplier-2',
    supplierSku: 'GRW-SUN-055',
    name: 'Glow Shield SPF50+ PA++++',
    description: 'Lightweight sunscreen with tone-up effect and blue light protection.',
    price: 38,
    currency: 'EUR',
    images: ['/products/glow-shield-spf.jpg'],
    category: 'sun-care',
    ingredients: ['Zinc Oxide', 'Niacinamide', 'Centella'],
    changeType: 'new',
    status: 'pending',
    receivedAt: '2024-03-15T08:15:00Z',
  },
]

export const supplierNotifications: SupplierNotification[] = [
  {
    id: 'notif-1',
    supplierId: 'supplier-1',
    type: 'sync_complete',
    title: 'Sync Complete',
    message: 'Hanbang Lab product catalog synced successfully. 3 new products pending review.',
    isRead: false,
    createdAt: '2024-03-15T09:30:00Z',
  },
  {
    id: 'notif-2',
    supplierId: 'supplier-2',
    type: 'price_change',
    title: 'Price Update Detected',
    message: 'Crystal Glow Toner price changed from €38 to €42.',
    isRead: false,
    createdAt: '2024-03-14T14:20:00Z',
  },
  {
    id: 'notif-3',
    supplierId: 'supplier-1',
    type: 'product_removed',
    title: 'Product Discontinued',
    message: 'Hanbang Herbal Night Cream has been discontinued by supplier.',
    isRead: true,
    createdAt: '2024-03-15T09:30:00Z',
  },
]

// ============ Market Availability ============
export const marketAvailability: MarketAvailability[] = [
  {
    productId: 'prod-1',
    productName: 'Luminous Glow Serum',
    productImage: '/products/luminous-glow-serum-1.jpg',
    markets: { UAE: 'visible_and_buyable', EU: 'visible_and_buyable', CA: 'visible_and_buyable' },
    complianceStatus: { UAE: 'compliant', EU: 'compliant', CA: 'compliant' },
    lastUpdated: '2024-03-10T14:00:00Z',
  },
  {
    productId: 'prod-2',
    productName: 'Hydra Cloud Cream',
    productImage: '/products/hydra-cloud-cream-1.jpg',
    markets: { UAE: 'visible_and_buyable', EU: 'visible_and_buyable', CA: 'visible_but_not_buyable' },
    complianceStatus: { UAE: 'compliant', EU: 'compliant', CA: 'pending_review' },
    lastUpdated: '2024-03-12T10:30:00Z',
    notes: 'Canada compliance documents pending review',
  },
  {
    productId: 'prod-4',
    productName: 'Aura Tone-Up Sun Cream',
    productImage: '/products/tone-up-sun-cream-1.jpg',
    markets: { UAE: 'visible_and_buyable', EU: 'visible_and_buyable', CA: 'pending_compliance' },
    complianceStatus: { UAE: 'compliant', EU: 'compliant', CA: 'missing' },
    lastUpdated: '2024-03-14T16:45:00Z',
    notes: 'Waiting for Health Canada sunscreen registration',
  },
  {
    productId: 'prod-8',
    productName: 'Pore Refining Serum',
    productImage: '/products/pore-refining-serum-1.jpg',
    markets: { UAE: 'hidden', EU: 'visible_and_buyable', CA: 'visible_and_buyable' },
    complianceStatus: { UAE: 'non_compliant', EU: 'compliant', CA: 'compliant' },
    lastUpdated: '2024-03-08T11:20:00Z',
    notes: 'BHA concentration exceeds UAE limit - reformulation needed',
  },
]

// ============ Compliance Records ============
export const complianceDocuments: ComplianceDocument[] = [
  {
    id: 'doc-1',
    productId: 'prod-1',
    type: 'COA',
    name: 'Certificate of Analysis - Luminous Glow Serum',
    fileUrl: '/docs/coa-luminous-glow-serum.pdf',
    fileSize: 245000,
    region: 'ALL',
    version: '2.1',
    uploadedAt: '2024-02-15T10:00:00Z',
    uploadedBy: 'Quality Team',
    expiresAt: '2025-02-15T10:00:00Z',
    status: 'compliant',
  },
  {
    id: 'doc-2',
    productId: 'prod-1',
    type: 'MSDS',
    name: 'Material Safety Data Sheet - Luminous Glow Serum',
    fileUrl: '/docs/msds-luminous-glow-serum.pdf',
    fileSize: 180000,
    region: 'ALL',
    version: '1.0',
    uploadedAt: '2024-01-20T14:30:00Z',
    uploadedBy: 'Quality Team',
    status: 'compliant',
  },
  {
    id: 'doc-3',
    productId: 'prod-4',
    type: 'STABILITY_REPORT',
    name: 'Stability Report - Aura Tone-Up Sun Cream',
    fileUrl: '/docs/stability-aura-sun.pdf',
    fileSize: 520000,
    region: 'ALL',
    version: '1.0',
    uploadedAt: '2024-03-01T09:00:00Z',
    uploadedBy: 'Lab Team',
    status: 'compliant',
  },
]

export const complaintRecords: ComplaintRecord[] = [
  {
    id: 'complaint-1',
    productId: 'prod-1',
    customerId: 'cust-123',
    region: 'UAE',
    type: 'adverse_reaction',
    severity: 'low',
    description: 'Customer reported mild tingling sensation after first use.',
    status: 'resolved',
    resolution: 'Normal reaction to Vitamin C. Customer advised to introduce gradually.',
    createdAt: '2024-02-20T08:00:00Z',
    resolvedAt: '2024-02-21T14:30:00Z',
    assignedTo: 'Support Team',
  },
  {
    id: 'complaint-2',
    productId: 'prod-2',
    region: 'EU',
    type: 'packaging',
    severity: 'medium',
    description: 'Pump dispenser not working on arrival.',
    status: 'investigating',
    createdAt: '2024-03-14T16:00:00Z',
    assignedTo: 'Quality Team',
  },
]

// ============ Translation Tasks ============
export const translationTasks: TranslationTask[] = [
  {
    id: 'trans-1',
    entityType: 'product',
    entityId: 'prod-1',
    entityName: 'Luminous Glow Serum',
    sourceLanguage: 'en',
    targetLanguages: ['ar', 'fr', 'de'],
    fieldsToTranslate: ['name', 'description', 'howToUse'],
    entries: [],
    priority: 'high',
    dueDate: '2024-03-20',
    status: 'in_progress',
    createdAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'trans-2',
    entityType: 'product',
    entityId: 'prod-7',
    entityName: 'Glass Skin Essence',
    sourceLanguage: 'en',
    targetLanguages: ['ar', 'fr'],
    fieldsToTranslate: ['name', 'description', 'shortDescription'],
    entries: [],
    priority: 'medium',
    status: 'pending',
    createdAt: '2024-03-14T11:00:00Z',
  },
]

export const translationEntries: TranslationEntry[] = [
  {
    id: 'entry-1',
    entityType: 'product',
    entityId: 'prod-1',
    entityName: 'Luminous Glow Serum',
    field: 'name',
    sourceLanguage: 'en',
    targetLanguage: 'ar',
    sourceText: 'Luminous Glow Serum',
    machineTranslation: 'سيروم التوهج اللامع',
    humanTranslation: 'سيروم الإشراق المضيء',
    finalText: 'سيروم الإشراق المضيء',
    status: 'approved',
    translatedBy: 'AI',
    reviewedBy: 'Fatima Al-Hassan',
    lastUpdatedAt: '2024-03-12T14:00:00Z',
  },
  {
    id: 'entry-2',
    entityType: 'product',
    entityId: 'prod-1',
    entityName: 'Luminous Glow Serum',
    field: 'description',
    sourceLanguage: 'en',
    targetLanguage: 'ar',
    sourceText: 'A breakthrough vitamin C serum that delivers intense brightening power while respecting sensitive skin.',
    machineTranslation: 'سيروم فيتامين سي متقدم يوفر قوة تفتيح مكثفة مع احترام البشرة الحساسة.',
    status: 'machine_translated',
    translatedBy: 'AI',
    lastUpdatedAt: '2024-03-12T14:00:00Z',
  },
  {
    id: 'entry-3',
    entityType: 'product',
    entityId: 'prod-1',
    entityName: 'Luminous Glow Serum',
    field: 'name',
    sourceLanguage: 'en',
    targetLanguage: 'fr',
    sourceText: 'Luminous Glow Serum',
    machineTranslation: 'Sérum Éclat Lumineux',
    humanTranslation: 'Sérum Éclat Lumineux',
    finalText: 'Sérum Éclat Lumineux',
    status: 'published',
    translatedBy: 'AI',
    reviewedBy: 'Marie Dubois',
    lastUpdatedAt: '2024-03-11T10:00:00Z',
  },
]

// ============ Media Assets ============
export const mediaAssets: MediaAsset[] = [
  {
    id: 'media-1',
    name: 'luminous-glow-serum-hero.jpg',
    type: 'image',
    originalUrl: '/media/luminous-glow-serum-hero.jpg',
    watermarkedUrl: '/media/luminous-glow-serum-hero-wm.jpg',
    thumbnailUrl: '/media/luminous-glow-serum-hero-thumb.jpg',
    width: 2400,
    height: 3200,
    fileSize: 2450000,
    mimeType: 'image/jpeg',
    focalPoint: { x: 50, y: 40 },
    crops: [
      { preset: 'website_hero', url: '/media/crops/lgs-hero.jpg', width: 1920, height: 800 },
      { preset: 'instagram_square', url: '/media/crops/lgs-ig.jpg', width: 1080, height: 1080 },
    ],
    tags: ['serum', 'hero', 'vitamin-c'],
    productIds: ['prod-1'],
    uploadedAt: '2024-02-01T10:00:00Z',
    uploadedBy: 'Creative Team',
  },
  {
    id: 'media-2',
    name: 'hydra-cloud-cream-lifestyle.jpg',
    type: 'image',
    originalUrl: '/media/hydra-cloud-cream-lifestyle.jpg',
    thumbnailUrl: '/media/hydra-cloud-cream-lifestyle-thumb.jpg',
    width: 3000,
    height: 2000,
    fileSize: 3200000,
    mimeType: 'image/jpeg',
    crops: [],
    tags: ['moisturizer', 'lifestyle', 'hydration'],
    productIds: ['prod-2'],
    uploadedAt: '2024-02-15T14:30:00Z',
    uploadedBy: 'Creative Team',
  },
]

// ============ Social Posts ============
export const socialPosts: SocialPost[] = [
  {
    id: 'post-1',
    channel: 'instagram',
    title: 'New Arrival: Glass Skin Essence',
    caption: 'Unlock the secret to Korean glass skin with our new Glass Skin Essence. Fermented botanicals meet modern science for the most luminous skin of your life. Shop now - link in bio.',
    mediaIds: ['media-1'],
    productIds: ['prod-7'],
    scheduledAt: '2024-03-18T14:00:00Z',
    status: 'scheduled',
    createdAt: '2024-03-15T10:00:00Z',
    createdBy: 'Marketing Team',
  },
  {
    id: 'post-2',
    channel: 'tiktok',
    title: 'Morning Routine with JISOO',
    caption: 'My 5-step Korean skincare morning routine using JISOO bestsellers. Which step is your favorite?',
    mediaIds: [],
    productIds: ['prod-1', 'prod-3', 'prod-4'],
    status: 'draft',
    createdAt: '2024-03-14T16:00:00Z',
    createdBy: 'Content Team',
  },
  {
    id: 'post-3',
    channel: 'instagram',
    title: 'Customer Love',
    caption: 'Real results from real customers. Thank you @skincare_lover for sharing your glass skin journey with us!',
    mediaIds: [],
    productIds: ['prod-1'],
    publishedAt: '2024-03-10T18:00:00Z',
    status: 'published',
    engagement: { likes: 2340, comments: 156, shares: 89, views: 45000 },
    createdAt: '2024-03-10T12:00:00Z',
    createdBy: 'Social Team',
  },
]

// ============ Analytics Dashboard ============
export const analyticsDashboard: AnalyticsDashboard = {
  period: 'month',
  totalRevenue: 284500,
  revenueGrowth: 12.5,
  totalOrders: 3420,
  ordersGrowth: 8.3,
  totalVisitors: 128000,
  visitorsGrowth: 15.2,
  conversionRate: 2.67,
  conversionGrowth: 0.3,
  averageOrderValue: 83.2,
  aovGrowth: 4.1,
  salesByDay: [
    { date: '2024-03-01', revenue: 8500, orders: 102, averageOrderValue: 83.3, conversionRate: 2.5 },
    { date: '2024-03-02', revenue: 9200, orders: 108, averageOrderValue: 85.2, conversionRate: 2.7 },
    { date: '2024-03-03', revenue: 7800, orders: 95, averageOrderValue: 82.1, conversionRate: 2.4 },
    { date: '2024-03-04', revenue: 10500, orders: 125, averageOrderValue: 84.0, conversionRate: 2.9 },
    { date: '2024-03-05', revenue: 9800, orders: 118, averageOrderValue: 83.1, conversionRate: 2.6 },
    { date: '2024-03-06', revenue: 11200, orders: 132, averageOrderValue: 84.8, conversionRate: 3.0 },
    { date: '2024-03-07', revenue: 8900, orders: 105, averageOrderValue: 84.8, conversionRate: 2.5 },
  ],
  salesByRegion: [
    { region: 'UAE', revenue: 142000, orders: 1680, visitors: 52000, conversionRate: 3.2, topProducts: ['prod-1', 'prod-2'], growth: 18.5 },
    { region: 'EU', revenue: 98500, orders: 1200, visitors: 48000, conversionRate: 2.5, topProducts: ['prod-1', 'prod-6'], growth: 8.2 },
    { region: 'CA', revenue: 44000, orders: 540, visitors: 28000, conversionRate: 1.9, topProducts: ['prod-3', 'prod-7'], growth: 5.8 },
  ],
  topProducts: [
    { productId: 'prod-1', productName: 'Luminous Glow Serum', productImage: '/products/luminous-glow-serum-1.jpg', revenue: 48500, unitsSold: 622, views: 18500, conversionRate: 3.4, returnRate: 1.2, averageRating: 4.8, trend: 'up' },
    { productId: 'prod-2', productName: 'Hydra Cloud Cream', productImage: '/products/hydra-cloud-cream-1.jpg', revenue: 38200, unitsSold: 588, views: 15200, conversionRate: 3.9, returnRate: 0.8, averageRating: 4.9, trend: 'up' },
    { productId: 'prod-6', productName: 'Cica Repair Ampoule', productImage: '/products/cica-repair-ampoule-1.jpg', revenue: 32400, unitsSold: 558, views: 12800, conversionRate: 4.4, returnRate: 0.5, averageRating: 4.9, trend: 'stable' },
    { productId: 'prod-7', productName: 'Glass Skin Essence', productImage: '/products/glass-skin-essence-1.jpg', revenue: 28600, unitsSold: 550, views: 14200, conversionRate: 3.9, returnRate: 0.9, averageRating: 4.8, trend: 'up' },
  ],
  topSuppliers: [
    { supplierId: 'supplier-2', supplierName: 'Glow Research', revenue: 124500, productCount: 52, averageRating: 4.7, topProducts: ['prod-1', 'prod-4', 'prod-8'] },
    { supplierId: 'supplier-1', supplierName: 'Hanbang Lab', revenue: 98200, productCount: 38, averageRating: 4.8, topProducts: ['prod-2', 'prod-7'] },
    { supplierId: 'supplier-3', supplierName: 'Seoul Skin Science', revenue: 61800, productCount: 28, averageRating: 4.9, topProducts: ['prod-3', 'prod-6'] },
  ],
  newCustomers: 1245,
  returningCustomers: 2175,
}

// ============ AI Insights ============
export const aiInsights: AIInsight[] = [
  {
    id: 'insight-1',
    type: 'sales',
    title: 'UAE Market Surge',
    summary: 'UAE sales increased 18.5% this month, driven by Vitamin C products.',
    details: 'The Luminous Glow Serum and Aura Tone-Up Sun Cream are performing exceptionally well in the UAE market. Consider increasing inventory allocation and featuring these products prominently in UAE marketing campaigns.',
    priority: 'high',
    actionItems: ['Increase UAE inventory by 20%', 'Feature in UAE homepage banner', 'Consider UAE-exclusive bundle'],
    relatedProducts: ['prod-1', 'prod-4'],
    relatedRegions: ['UAE'],
    createdAt: '2024-03-15T06:00:00Z',
    isRead: false,
    isDismissed: false,
  },
  {
    id: 'insight-2',
    type: 'inventory',
    title: 'Low Stock Alert',
    summary: '3 bestselling products are running low on inventory.',
    details: 'Hydra Cloud Cream, Cica Repair Ampoule, and Velvet Matte Lip Tint (Nude Blush) have less than 2 weeks of inventory remaining based on current sales velocity.',
    priority: 'high',
    actionItems: ['Contact suppliers for expedited shipment', 'Enable back-in-stock notifications'],
    relatedProducts: ['prod-2', 'prod-6', 'prod-5'],
    createdAt: '2024-03-15T06:00:00Z',
    isRead: false,
    isDismissed: false,
  },
  {
    id: 'insight-3',
    type: 'compliance',
    title: 'Canada Compliance Gap',
    summary: '2 products pending Health Canada approval.',
    details: 'Aura Tone-Up Sun Cream and Hydra Cloud Cream are awaiting compliance documentation for the Canadian market. This is blocking potential revenue of approximately €8,500/month.',
    priority: 'medium',
    actionItems: ['Follow up with regulatory team', 'Prepare alternative formulations if needed'],
    relatedProducts: ['prod-4', 'prod-2'],
    relatedRegions: ['CA'],
    createdAt: '2024-03-14T12:00:00Z',
    isRead: true,
    isDismissed: false,
  },
  {
    id: 'insight-4',
    type: 'translation',
    title: 'Arabic Content Opportunity',
    summary: '12 products missing Arabic translations.',
    details: 'Expanding Arabic content coverage could increase UAE conversion by an estimated 15% based on regional analytics.',
    priority: 'medium',
    actionItems: ['Prioritize bestseller translations', 'Review machine translations for accuracy'],
    createdAt: '2024-03-13T10:00:00Z',
    isRead: true,
    isDismissed: false,
  },
]

// ============ Admin Dashboard ============
export const adminDashboardData: AdminDashboardData = {
  overview: {
    totalSales: 284500,
    salesGrowth: 12.5,
    totalOrders: 3420,
    ordersGrowth: 8.3,
    conversionRate: 2.67,
    conversionGrowth: 0.3,
    pendingSupplierProducts: 16,
    lowStockAlerts: 3,
    regionRestrictionAlerts: 4,
    translationTasks: 8,
    socialTasks: 5,
  },
  recentActivity: [
    { id: 'act-1', type: 'order', title: 'New Order #JIS-3421', description: 'Order placed for €156.00 (UAE)', timestamp: '2024-03-15T10:45:00Z', icon: 'shopping-bag' },
    { id: 'act-2', type: 'supplier', title: 'Supplier Sync', description: 'Hanbang Lab synced 3 new products', timestamp: '2024-03-15T09:30:00Z', icon: 'refresh-cw' },
    { id: 'act-3', type: 'product', title: 'Product Approved', description: 'Centella Recovery Mask published to store', timestamp: '2024-03-14T16:20:00Z', icon: 'check-circle' },
    { id: 'act-4', type: 'compliance', title: 'Document Uploaded', description: 'COA uploaded for Luminous Glow Serum', timestamp: '2024-03-14T14:00:00Z', icon: 'file-text' },
    { id: 'act-5', type: 'translation', title: 'Translation Complete', description: 'French translations approved for 5 products', timestamp: '2024-03-14T11:30:00Z', icon: 'globe' },
  ],
  topProducts: analyticsDashboard.topProducts,
  aiInsights: aiInsights.filter(i => !i.isDismissed).slice(0, 4),
  pendingActions: [
    { id: 'pa-1', type: 'supplier_review', title: 'Review Supplier Products', description: '16 products awaiting review from 3 suppliers', priority: 'high', link: '/admin/suppliers' },
    { id: 'pa-2', type: 'compliance_update', title: 'Upload Compliance Docs', description: '2 products need compliance documents for Canada', priority: 'high', dueDate: '2024-03-20', link: '/admin/compliance' },
    { id: 'pa-3', type: 'translation_review', title: 'Review Translations', description: '8 Arabic translations pending human review', priority: 'medium', link: '/admin/translations' },
    { id: 'pa-4', type: 'social_approval', title: 'Approve Social Posts', description: '3 scheduled posts need approval', priority: 'low', link: '/admin/social' },
  ],
}

// ============ Admin Orders ============
export const adminOrders: AdminOrder[] = [
  {
    id: 'order-1',
    orderNumber: 'JIS-3421',
    status: 'processing',
    items: [
      { id: 'oi-1', product: {} as any, quantity: 2, price: 78 },
      { id: 'oi-2', product: {} as any, quantity: 1, price: 65 },
    ],
    subtotal: 221,
    tax: 11.05,
    shipping: 0,
    discount: 22.10,
    total: 209.95,
    currency: 'AED',
    shippingAddress: {
      id: 'addr-1',
      firstName: 'Aisha',
      lastName: 'Al-Mansoori',
      address1: '123 Palm Jumeirah',
      city: 'Dubai',
      postalCode: '00000',
      country: 'UAE',
      phone: '+971 50 123 4567',
    },
    billingAddress: {
      id: 'addr-1',
      firstName: 'Aisha',
      lastName: 'Al-Mansoori',
      address1: '123 Palm Jumeirah',
      city: 'Dubai',
      postalCode: '00000',
      country: 'UAE',
      phone: '+971 50 123 4567',
    },
    paymentMethod: 'Credit Card',
    createdAt: '2024-03-15T10:45:00Z',
    updatedAt: '2024-03-15T11:00:00Z',
    estimatedDelivery: '2024-03-18',
    customerEmail: 'aisha@example.com',
    customerName: 'Aisha Al-Mansoori',
    communicationHistory: [
      { id: 'comm-1', type: 'email', subject: 'Order Confirmation', content: 'Thank you for your order...', sentAt: '2024-03-15T10:46:00Z', sentBy: 'System' },
    ],
    timeline: [
      { id: 'tl-1', type: 'order_placed', title: 'Order Placed', description: 'Customer placed order', timestamp: '2024-03-15T10:45:00Z' },
      { id: 'tl-2', type: 'payment_confirmed', title: 'Payment Confirmed', description: 'Payment processed successfully', timestamp: '2024-03-15T10:46:00Z' },
      { id: 'tl-3', type: 'processing', title: 'Processing', description: 'Order is being prepared', timestamp: '2024-03-15T11:00:00Z', actor: 'Warehouse' },
    ],
  },
]

// ============ Admin Customers ============
export const adminCustomers: AdminCustomer[] = [
  {
    id: 'cust-1',
    email: 'aisha@example.com',
    firstName: 'Aisha',
    lastName: 'Al-Mansoori',
    phone: '+971 50 123 4567',
    avatar: '/avatars/aisha.jpg',
    addresses: [],
    wishlist: ['prod-1', 'prod-7'],
    recentlyViewed: ['prod-1', 'prod-2', 'prod-3'],
    points: 2450,
    tier: 'gold',
    createdAt: '2023-06-15T10:00:00Z',
    totalSpent: 1856.50,
    orderCount: 12,
    averageOrderValue: 154.70,
    lastOrderAt: '2024-03-15T10:45:00Z',
    isVIP: true,
    segment: 'loyal',
    notes: 'Prefers express shipping. Sensitive skin - recommend Cica products.',
    tags: ['VIP', 'Sensitive Skin', 'Express Shipping'],
    communicationPreferences: { email: true, sms: true, push: false },
  },
  {
    id: 'cust-2',
    email: 'sophie@example.com',
    firstName: 'Sophie',
    lastName: 'Martin',
    addresses: [],
    wishlist: ['prod-2'],
    recentlyViewed: ['prod-2', 'prod-6'],
    points: 850,
    tier: 'silver',
    createdAt: '2023-11-20T14:00:00Z',
    totalSpent: 542.00,
    orderCount: 5,
    averageOrderValue: 108.40,
    lastOrderAt: '2024-02-28T16:30:00Z',
    isVIP: false,
    segment: 'regular',
    tags: ['France', 'Anti-Aging'],
    communicationPreferences: { email: true, sms: false, push: true },
  },
]

export const topProductsPerformance: ProductPerformance[] = [
  { productId: 'prod-1', productName: 'Luminous Glow Serum', productImage: '/products/luminous-glow-serum-1.jpg', revenue: 48500, unitsSold: 622, views: 18500, conversionRate: 3.4, returnRate: 1.2, averageRating: 4.8, trend: 'up' },
  { productId: 'prod-2', productName: 'Hydra Cloud Cream', productImage: '/products/hydra-cloud-cream-1.jpg', revenue: 38200, unitsSold: 588, views: 15200, conversionRate: 3.9, returnRate: 0.8, averageRating: 4.9, trend: 'up' },
  { productId: 'prod-6', productName: 'Cica Repair Ampoule', productImage: '/products/cica-repair-ampoule-1.jpg', revenue: 32400, unitsSold: 558, views: 12800, conversionRate: 4.4, returnRate: 0.5, averageRating: 4.9, trend: 'stable' },
  { productId: 'prod-7', productName: 'Glass Skin Essence', productImage: '/products/glass-skin-essence-1.jpg', revenue: 28600, unitsSold: 550, views: 14200, conversionRate: 3.9, returnRate: 0.9, averageRating: 4.8, trend: 'up' },
  { productId: 'prod-3', productName: 'Gentle Cloud Foam Cleanser', productImage: '/products/gentle-foam-cleanser-1.jpg', revenue: 22400, unitsSold: 700, views: 11500, conversionRate: 6.1, returnRate: 0.3, averageRating: 4.7, trend: 'stable' },
]
